### ISSUE TITLE
Add Card Flip

### ISSUE THREAD

**Issue by yash-k9** [theapache64/twyper#2]
Hi @theapache64 , Twyper looks cool. I added the Card Flip. Can I raise a PR?

**Comment by theapache64** [comment]
Hey Yash,
Sorry, I don't understand how a flip will work in swipeable cards. Do you have a demo video of that? Also what the end API would look like?

**Comment by yash-k9** [comment]
It'd look similar to deck of flash cards, and the end api would have the front and back composable
```@Composable
inline fun <reified T> TwyperFlip(
    items: List<T>,
    onItemRemoved: (T, SwipedOutDirection) -> Unit,
    onEmpty: () -> Unit = {},
    twyperController: TwyperController = rememberTwyperController(),
    stackCount: Int = 2,
    paddingBetweenCards: Float = 40f,
    modifier: Modifier = Modifier,
    cardModifier: () -> Modifier,
    crossinline front: @Composable (T) -> Unit,
    crossinline back: @Composable (T) -> Unit
) 
```
https://user-images.githubusercontent.com/59912430/155744293-19700d78-c783-471c-97e0-61d265ff952e.mp4

**Comment by theapache64** [comment]
Wow. this looks totally cool. Please raise the PR 🚀

**Comment by yash-k9** [comment]
:)) Raised the PR

**Comment by theapache64** [comment]
#3
