### ISSUE TITLE
Update release to include latest features

### ISSUE THREAD

**Issue by Sal7one** [theapache64/twyper#5]
### Problem: Missing features 
I'm trying to use the stack count and paddingBetweenCards as parameter, but this PR is not included in the built version #1 

It's also is not included in the available release on Github and jitpack.io

**Comment by theapache64** [comment]
@Sal7one Sorry for the delayed reply. Can you try with `v0.0.4`? Tagged the release just 2 hours ago

**Comment by Sal7one** [comment]
@theapache64 Thanks a bunch! It's working great.
Apologies I did not see it wasn't released in the first place. Sorry if I rushed anything.

**Comment by theapache64** [comment]
@Sal7one Not at all. The issue was on my side. I forgot to tag the release and push it to remote :D Anyway, Glad it worked for you. Feel free to create an issue if you want to start any conversation
